# Colors (Gruvbox dark)
#colors:
#  primary:
#    background: '0x1E1E1E'
#    foreground: '0xD4D4D4'
#
#  normal:
#    black:   '0x1E1E1E'
#    red:     '0xF44747'
#    green:   '0x608B4E'
#    yellow:  '0xD7BA7D'
#    blue:    '0x569CD6'
#    magenta: '0xC586C0'
#    cyan:    '0x9CDCFE'
#    white:   '0xD4D4D4'
# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '0x1E1E1E'
# soft contrast background = = '#32302f'
foreground = '0xD4D4D4'

# Normal colors
[colors.normal]
black=   '0x1E1E1E'
red=     '0xF44747'
green=   '0x608B4E'
yellow=  '0xD7BA7D'
blue=    '0x569CD6'
magenta= '0xC586C0'
cyan=    '0x9CDCFE'
white=   '0xD4D4D4'
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
